
// This file has been generated by the GUI designer. Do not modify.
namespace libTerminus
{
	public partial class cWelcome
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget libTerminus.cWelcome
			global::Stetic.BinContainer.Attach (this);
			this.Name = "libTerminus.cWelcome";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
