
// This file has been generated by the GUI designer. Do not modify.
namespace libTerminus
{
	public partial class cRegex
	{
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView Expression;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TextView DataSource;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget libTerminus.cRegex
			global::Stetic.BinContainer.Attach (this);
			this.Name = "libTerminus.cRegex";
			// Container child libTerminus.cRegex.Gtk.Container+ContainerChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 354;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.Expression = new global::Gtk.TextView ();
			this.Expression.CanFocus = true;
			this.Expression.Name = "Expression";
			this.Expression.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindow1.Add (this.Expression);
			this.hpaned1.Add (this.GtkScrolledWindow1);
			global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow1]));
			w2.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.DataSource = new global::Gtk.TextView ();
			this.DataSource.CanFocus = true;
			this.DataSource.Name = "DataSource";
			this.DataSource.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindow2.Add (this.DataSource);
			this.hpaned1.Add (this.GtkScrolledWindow2);
			this.Add (this.hpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
