
// This file has been generated by the GUI designer. Do not modify.
namespace libTerminus
{
	public partial class cKeyBoard
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.Expander expander2;
		private global::Gtk.Label label2;
		private global::Gtk.Label GtkLabel;
		private global::Gtk.Expander expander3;
		private global::Gtk.Label label3;
		private global::Gtk.Label GtkLabel1;
		private global::Gtk.Expander expander4;
		private global::Gtk.Label label4;
		private global::Gtk.Label GtkLabel2;
		private global::Gtk.Expander expander5;
		private global::Gtk.Label label5;
		private global::Gtk.Label GtkLabel3;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget libTerminus.cKeyBoard
			this.Name = "libTerminus.cKeyBoard";
			this.Title = global::Mono.Unix.Catalog.GetString ("Tastaturkombinationen");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("libTerminus.Programm.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child libTerminus.cKeyBoard.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.expander2 = new global::Gtk.Expander (null);
			this.expander2.CanFocus = true;
			this.expander2.Name = "expander2";
			this.expander2.Expanded = true;
			// Container child expander2.Gtk.Container+ContainerChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>STRG + N</b> Neue Datei anlegen\n<b>STRG + O</b> Datei öffnen\n<b>STRG + S</b> Datei speichern\n<b>STRG + ALT + S</b> Datei speichern unter\n<b>STRG + K</b> Dateikopie speichern\n<b>STRG + E</b> Datei schließen");
			this.label2.UseMarkup = true;
			this.expander2.Add (this.label2);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Dateimanagement");
			this.GtkLabel.UseUnderline = true;
			this.expander2.LabelWidget = this.GtkLabel;
			this.vbox3.Add (this.expander2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.expander2]));
			w2.Position = 0;
			w2.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.expander3 = new global::Gtk.Expander (null);
			this.expander3.CanFocus = true;
			this.expander3.Name = "expander3";
			this.expander3.Expanded = true;
			// Container child expander3.Gtk.Container+ContainerChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>STRG + Q</b> Terminus beenden\n<b>STRG + I</b> HIlfe im Web aufrufen\n<b>STRG + Y</b> Informationen über diese Version anzeigen\n<b>STRG + B</b> Fehler melden\n<b>STRG + I</b> Programminfo anzeigen\n<b>STRG + P</b> Einstellungen\n<b>STRG + L</b> Bibliothek einblenden\n<b>STRG + ALT + K</b> Diesen DIalog einblenden");
			this.label3.UseMarkup = true;
			this.expander3.Add (this.label3);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("Programm");
			this.GtkLabel1.UseUnderline = true;
			this.expander3.LabelWidget = this.GtkLabel1;
			this.vbox3.Add (this.expander3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.expander3]));
			w4.Position = 1;
			w4.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.expander4 = new global::Gtk.Expander (null);
			this.expander4.CanFocus = true;
			this.expander4.Name = "expander4";
			this.expander4.Expanded = true;
			// Container child expander4.Gtk.Container+ContainerChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>STRG + Z</b> Rückgängig\n<b>STRG + W</b> Wiederholen\n<b>STRG + X</b> Ausschneiden\n<b>STRG + V</b> Einfügen\n<b>STRG + C</b> Kopieren");
			this.label4.UseMarkup = true;
			this.expander4.Add (this.label4);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("Bearbeitungsbefehle");
			this.GtkLabel2.UseUnderline = true;
			this.expander4.LabelWidget = this.GtkLabel2;
			this.vbox3.Add (this.expander4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.expander4]));
			w6.Position = 2;
			w6.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.expander5 = new global::Gtk.Expander (null);
			this.expander5.CanFocus = true;
			this.expander5.Name = "expander5";
			this.expander5.Expanded = true;
			// Container child expander5.Gtk.Container+ContainerChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>STRG + Leer</b> Ausdruck verarbeiten\n<b>STRG + ALT + SUPER + C</b> Ausdruck und Daten und Ausgabe leeren\n<b>STRG + ALT + T</b> Export nach *.txt\n<b>STRG + ALT + C</b> Export nach *.csv\n<b>STRG + ALT + H</b> Export nach Hypertext\n<b>STRG + ALT + U</b> Ausdrücke wiederherstellen");
			this.label5.UseMarkup = true;
			this.label5.Wrap = true;
			this.expander5.Add (this.label5);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("Ausdrucksverarbeitung");
			this.GtkLabel3.UseUnderline = true;
			this.expander5.LabelWidget = this.GtkLabel3;
			this.vbox3.Add (this.expander5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.expander5]));
			w8.Position = 3;
			w8.Expand = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 468;
			this.DefaultHeight = 573;
			this.Show ();
		}
	}
}
