
// This file has been generated by the GUI designer. Do not modify.
namespace libTerminus
{
	public partial class cHelp
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Expander expander1;
		private global::Gtk.Label label1;
		private global::Gtk.Label GtkLabel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget libTerminus.cHelp
			this.Name = "libTerminus.cHelp";
			this.Title = global::Mono.Unix.Catalog.GetString ("Hilfe");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("libTerminus.Programm.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child libTerminus.cHelp.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.expander1 = new global::Gtk.Expander (null);
			this.expander1.CanFocus = true;
			this.expander1.Name = "expander1";
			this.expander1.Expanded = true;
			// Container child expander1.Gtk.Container+ContainerChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>STRG + N </b> Neue Datei anlegen");
			this.label1.UseMarkup = true;
			this.expander1.Add (this.label1);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Hauptfunktionen");
			this.GtkLabel.UseUnderline = true;
			this.expander1.LabelWidget = this.GtkLabel;
			this.vbox1.Add (this.expander1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.expander1]));
			w2.Position = 0;
			w2.Expand = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
