#!/bin/bash
echo "Working Path: $dirname($BASH_SOURCE)"
#workingpath = "$BASH_SOURCE"
if [ -f "$HOME/.terminus" ] 
then
echo "Configuration file ($HOME/.terminus) is present, able to launch terminus"
	if [ $BASH_SOURCE = "/usr/bin/terminus" ]
	then
		exec /usr/bin/mono "/usr/share/terminus/Terminus.exe" "$@"
	else
		exec /usr/bin/mono "$(dirname $BASH_SOURCE)/Terminus.exe" "$@"
	fi
else
	echo "Configuration file not found. Trying to restore config file."
	echo "Maybe your installation was corrupted."
		if [ $BASH_SOURCE = "/usr/bin/terminus" ]
		then
			echo "Terminus is installed. Trying to get default config from \"/usr/share/\"."
			exec cp "/usr/share/terminus/Boot/Config/terminus.conf" "$HOME/.terminus"
		else
			echo "Terminus is not installed. Trying to get default config from \"$(dirname $BASH_SOURCE)\""
			exec cp "$(dirname $BASH_SOURCE)/Boot/Config/terminus.conf" "$HOME/.terminus"
	fi
	echo "You can now try to start terminus"
fi


